### PR TITLE
add functions for std_hilbert

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by tthsqe12** [comment]
@thofma do you know anything about this broken pipe?

**Comment by thofma** [comment]
Which one?

**Comment by tthsqe12** [comment]
1.6 ubuntu latest
https://github.com/oscar-system/libsingular-julia/actions/runs/3640460912/jobs/6145160424

**Comment by thofma** [comment]
no clue, I have restarted it

**Comment by tthsqe12** [comment]
I have seen this error sometime when running tests locally with certain combinations of the packages.

**Comment by tthsqe12** [comment]
I don't think so. I will try to reproduce tomorrow.

**Comment by tthsqe12** [comment]
Very strange. I have known for a while that the test code writes a file `test/sing4ti2.converted`. But, the whole source tree is readonly in a non-deved installation. How did this ever work before?

**Comment by thofma** [comment]
Not sure. CI has to clone the repo anyway and thus works more like in the dev'ed situation.

**Comment by thofma** [comment]
ok, so new Singular.jl release?

**Comment by tthsqe12** [comment]
0.15.1 for the broken pipe?
then, 0.16.0 for the new hilbert stuff?

**Comment by thofma** [comment]
dunno

**Pull request merged**
