### PR TITLE
OscarCI: add github token and force precompilation

### PR DESCRIPTION
**Pull request by benlorenz**

### CODE REVIEW

**Comment by thofma** [comment]
We also have https://github.com/oscar-system/libsingular-julia/blob/1521ad223a44e31d244c2b66d95dc34fdb019ea2/OscarCI.toml#L5-L7
Is this still relevant?

**Comment by benlorenz** [comment]
> We also have
> 
> https://github.com/oscar-system/libsingular-julia/blob/1521ad223a44e31d244c2b66d95dc34fdb019ea2/OscarCI.toml#L5-L7
> 
> 
> Is this still relevant?

It seems so, yes. I just tried to add 1.6 to the list and the weird mixing reappeared.

**Comment by thofma** [comment]
Should we merge to get the token fix in?

**Comment by benlorenz** [comment]
Lets wait until I can fix the override issue, the problem seems to be that precompilation is not triggered automatically after the override is placed into the temporary depot and then Singular.jl uses the cached path to the default artifact in the precompiled code.
I just need to figure out a nice way to force that, maybe by just `touch`ing the right files.

**Comment by thofma** [comment]
`Pkg.precompile()`?

**Comment by benlorenz** [comment]
> `Pkg.precompile()`?

no, that doesn't help, julia seems to think everything is up-to-date.

**Comment by thofma** [comment]
Good to go?

**Comment by benlorenz** [comment]
> Good to go?

yes

**Pull request merged**
