### PR TITLE
proper num/den and gcdx + normalize for QQ

### PR DESCRIPTION
**Pull request by tthsqe12**
goes with https://github.com/oscar-system/Singular.jl/pull/421

### CODE REVIEW

**Comment by thofma** [comment]
@benlorenz There is something weird going on. The MacOS build cannot find the Singular.jl branch in the fork of @tthsqe12:
https://github.com/oscar-system/libsingular-julia/pull/25/checks?check_run_id=2501766523#step:6:51
But the Ubuntu build can:
https://github.com/oscar-system/libsingular-julia/pull/25/checks?check_run_id=2501766483#step:6:51

Also it seems to not compile the right version on Ubtunu + julia master.

**Comment by benlorenz** [comment]
That seems quite weird, regarding the non-detection of the branch we might be hitting some github rate-limiting for the API calls. I assumed that this would not be that strict when run from github actions but we might be able to fix this by adding `GITHUB_TOKEN`.

Right now I really don't know why it would build a wrong version / branch, it should not touch the current checkout and the build+override stuff is done by the `run.jl` script. I will have a closer look later today.

**Comment by thofma** [comment]
(I was hitting the github quota today in a Nemo PR, but could fix it by restarting.)

**Comment by thofma** [comment]
Ubuntu + julia master seems to really be a problem. I can reproduce the error locally @tthsqe12.

**Comment by benlorenz** [comment]
The branch lookup seems to work reliably in #27 with the github_token, so once that is merged closing and reopening this ticket should fix that issue.

But there seems to be something quite weird with the override. I can reproduce that failure also with julia 1.6.1 locally and looking at the `LD_DEBUG=files` output shows that `libsingular_julia.so` is loaded twice in the same process, once from the override directory and once from the default depot:
```
     15453:     file=/tmp/libsing/libsingular-julia/install/lib/libsingular_julia.so [0];  dynamically loaded by /software/julia/julia-1.6.1/bin/../lib/julia/libjulia-internal.so.1 [0]
     15453:     file=/tmp/libsing/libsingular-julia/install/lib/libsingular_julia.so [0];  generating link map
     15453:     activating NODELETE for /tmp/libsing/libsingular-julia/install/lib/libsingular_julia.so [0]
     15453:     calling init: /tmp/libsing/libsingular-julia/install/lib/libsingular_julia.so
     15453:     opening file=/tmp/libsing/libsingular-julia/install/lib/libsingular_julia.so [0]; direct_opencount=1
     15453:     file=/software/julia/depots/julia-161/artifacts/88f35a35a2aa71e5562d247d7c274efd12acfcb9/lib/libsingular_julia.so [0];  dynamically loaded by /software/julia/julia-1.6.1/bin/../lib/julia/libjulia-internal.so.1 [0]
     15453:     file=/software/julia/depots/julia-161/artifacts/88f35a35a2aa71e5562d247d7c274efd12acfcb9/lib/libsingular_julia.so [0];  generating link map
     15453:     calling init: /software/julia/depots/julia-161/artifacts/88f35a35a2aa71e5562d247d7c274efd12acfcb9/lib/libsingular_julia.so
     15453:     opening file=/software/julia/depots/julia-161/artifacts/88f35a35a2aa71e5562d247d7c274efd12acfcb9/lib/libsingular_julia.so [0]; direct_opencount=1
     15453:     calling fini: /tmp/libsing/libsingular-julia/install/lib/libsingular_julia.so [0]
     15453:     calling fini: /software/julia/depots/julia-161/artifacts/88f35a35a2aa71e5562d247d7c274efd12acfcb9/lib/libsingular_julia.so [0]
```

**Comment by thofma** [comment]
Hm, bad. I noticed that the latest version of `libsingular_julia` is `0.10.*`, which is not used by the latest Singular release, but by Singular master branch (and the `fix_reference_bugs` branch). As far as I see, after instantiating we end up with `0.9.*`, which is the `libsingular_julia` version used by the latest Singular release.

Could this somehow be a problem?

**Comment by tthsqe12** [comment]
@thofma @benlorenz  thanks all yall.

**Pull request merged**
