### PR TITLE
Avoid trivial wrappers

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Review by mohamed-barakat — APPROVED** [review]

**Comment by wbhart** [comment]
These were necessary in an earlier version of CxxWrap. Julia would crash without them. We don't know why.

**Comment by thofma** [comment]
I assume you tested this?

**Comment by fingolfin** [comment]
@thofma I did limited tests only. In any case, to feel comfortable about merging *anything* here, I'd like to have proper CI test run on PRs (it's too easy to screw up a manual tests). For this we ideally should extend the setup started by @benlorenz to cover this: i.e. run CI tests here which build libsingular_julia_jll here, then inject them, and run the test suite of Singular.jl in a matching branch. I've begun some minimalistic CI in PR #16 but that's clearly not yet enough. Help to convert that to a full test setup would be highly welcome.

**Comment by fingolfin** [comment]
Using PR #17 I found one minor issue here, will fix it later

**Comment by fingolfin** [comment]
(Waiting for PR I #17 to be merged; then I'll rebase this)

**Comment by fingolfin** [comment]
I've rebased this, and it passes all tests.

**Pull request merged**
